--[[
	© 2015 Novabox.org do not share, re-distribute or modify
	without permission of its author (dragonfabledonnny@gmail.com).
--]]

local PLUGIN = PLUGIN

PLUGIN:AddContainerType( 1, "Refridgerator", 6 );
PLUGIN:AddContainerItem( "orange", 2 );
PLUGIN:AddContainerItem( "bananabunch", 8 );
PLUGIN:AddContainerItem( "banana", 2 );
PLUGIN:AddContainerItem( "bottle1", 4 );
PLUGIN:AddContainerItem( "beer1", 4 );
PLUGIN:AddContainerItem( "beer2", 4 );
PLUGIN:AddContainerItem( "whiskey", 4 );
PLUGIN:AddContainerItem( "bottle5", 4 );
PLUGIN:AddContainerItem( "bottle6", 4 );
PLUGIN:AddContainerItem( "brandy", 4 );
PLUGIN:AddContainerItem( "bottle9", 4 );
PLUGIN:AddContainerItem( "milkcarton", 2 );
PLUGIN:AddContainerItem( "milk", 4 );
PLUGIN:AddContainerItem( "soda1", 2 );
PLUGIN:AddContainerItem( "soda2", 2 );
PLUGIN:AddContainerItem( "soda3", 2 );
PLUGIN:AddContainerItem( "takeout", 3 );
PLUGIN:AddContainerItem( "water", 2 );
PLUGIN:AddContainerItem( "watermelon", 8 );

PLUGIN:AddContainerType( 2, "Kitchen Cupboard", 6 );
PLUGIN:AddContainerItem( "bandage", 5 );
PLUGIN:AddContainerItem( "bucket", 3 );
PLUGIN:AddContainerItem( "carbattery", 10 );
PLUGIN:AddContainerItem( "drawer", 2 );
PLUGIN:AddContainerItem( "electronicscrap", 5 );
PLUGIN:AddContainerItem( "extinguisher", 3 );
PLUGIN:AddContainerItem( "hammer", 9 );
PLUGIN:AddContainerItem( "painkillers", 3 );
PLUGIN:AddContainerItem( "jarbig", 3 );
PLUGIN:AddContainerItem( "lamp", 6 );
PLUGIN:AddContainerItem( "paint", 7 );
PLUGIN:AddContainerItem( "pipe", 9 );
PLUGIN:AddContainerItem( "paper", 3 );
PLUGIN:AddContainerItem( "plasticbucket", 3 );
PLUGIN:AddContainerItem( "pliers", 5 );
PLUGIN:AddContainerItem( "plug", 6 );
PLUGIN:AddContainerItem( "pot", 9 );
PLUGIN:AddContainerItem( "radio", 10 );
PLUGIN:AddContainerItem( "metal", 5 );
PLUGIN:AddContainerItem( "scrapwood", 5 );
PLUGIN:AddContainerItem( "skull", 64 );
PLUGIN:AddContainerItem( "smallpot", 2 );
PLUGIN:AddContainerItem( "soda1", 4 );
PLUGIN:AddContainerItem( "soda2", 4 );
PLUGIN:AddContainerItem( "soda3", 4 );
PLUGIN:AddContainerItem( "survivalguide", 128 );
PLUGIN:AddContainerItem( "teapot", 2 );
PLUGIN:AddContainerItem( "water", 3 );
PLUGIN:AddContainerItem( "wrench", 9 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "cereal", 2 );
PLUGIN:AddContainerItem( "cannedbeans", 2 );
PLUGIN:AddContainerItem( "cannedcorn", 2 );
PLUGIN:AddContainerItem( "cannedyams", 2 );
PLUGIN:AddContainerItem( "concentratedmilk", 4 );
PLUGIN:AddContainerItem( "rationjar", 6 );

PLUGIN:AddContainerType( 3, "Wardrobe", 5 );
PLUGIN:AddContainerItem( "tshirt", 1 );
PLUGIN:AddContainerItem( "bandage", 6 );
PLUGIN:AddContainerItem( "doll", 16 );
PLUGIN:AddContainerItem( "drawer", 8 );
PLUGIN:AddContainerItem( "electronicscrap", 8 );
PLUGIN:AddContainerItem( "money", 3 );
PLUGIN:AddContainerItem( "paper", 3 );
PLUGIN:AddContainerItem( "photo", 2 );
PLUGIN:AddContainerItem( "pillow", 10 );
PLUGIN:AddContainerItem( "shoe", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );
PLUGIN:AddContainerItem( "skull", 64 );
PLUGIN:AddContainerItem( "spine", 64 );
PLUGIN:AddContainerItem( "survivalguide", 128 );
PLUGIN:AddContainerItem( "knife", 7 );

PLUGIN:AddContainerType( 4, "Bathroom Cupboard", 4 );
PLUGIN:AddContainerItem( "toothbrushes", 2 );
PLUGIN:AddContainerItem( "photo", 10 );
PLUGIN:AddContainerItem( "painkillers", 3 );
PLUGIN:AddContainerItem( "jarbig", 3 );
PLUGIN:AddContainerItem( "bandage", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );

PLUGIN:AddContainerType( 5, "Scrap Box", 5 );
PLUGIN:AddContainerItem( "plank", 2 );
PLUGIN:AddContainerItem( "carbattery", 10 );
PLUGIN:AddContainerItem( "cinderblock", 10 );
PLUGIN:AddContainerItem( "electronicscrap", 2 );
PLUGIN:AddContainerItem( "lever", 2 );
PLUGIN:AddContainerItem( "metalplate", 2 );
PLUGIN:AddContainerItem( "rebars", 2 );
PLUGIN:AddContainerItem( "metal", 2 );
PLUGIN:AddContainerItem( "scrapwood", 2 );
PLUGIN:AddContainerItem( "tire", 5 );

PLUGIN:AddContainerType( 6, "Toolbox", 2 );
PLUGIN:AddContainerItem( "hammer", 6 );
PLUGIN:AddContainerItem( "pliers", 4 );
PLUGIN:AddContainerItem( "tireiron", 6 );
PLUGIN:AddContainerItem( "wrench", 6 );
PLUGIN:AddContainerItem( "knife", 7 );

PLUGIN:AddContainerType( 7, "Food Stash", 12 );
PLUGIN:AddContainerItem( "orange", 2 );
PLUGIN:AddContainerItem( "bananabunch", 2 );
PLUGIN:AddContainerItem( "banana", 2 );
PLUGIN:AddContainerItem( "bottle1", 4 );
PLUGIN:AddContainerItem( "beer1", 4 );
PLUGIN:AddContainerItem( "beer2", 4 );
PLUGIN:AddContainerItem( "whiskey", 4 );
PLUGIN:AddContainerItem( "bottle5", 4 );
PLUGIN:AddContainerItem( "bottle6", 4 );
PLUGIN:AddContainerItem( "brandy", 4 );
PLUGIN:AddContainerItem( "bottle9", 4 );
PLUGIN:AddContainerItem( "milkcarton", 2 );
PLUGIN:AddContainerItem( "milk", 2 );
PLUGIN:AddContainerItem( "soda1", 2 );
PLUGIN:AddContainerItem( "soda2", 2 );
PLUGIN:AddContainerItem( "soda3", 2 );
PLUGIN:AddContainerItem( "takeout", 2 );
PLUGIN:AddContainerItem( "water", 2 );
PLUGIN:AddContainerItem( "watermelon", 2 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "cereal", 2 );
PLUGIN:AddContainerItem( "cannedbeans", 2 );
PLUGIN:AddContainerItem( "cannedcorn", 2 );
PLUGIN:AddContainerItem( "cannedyams", 2 );
PLUGIN:AddContainerItem( "concentratedmilk", 4 );
PLUGIN:AddContainerItem( "rationjar", 4 );


PLUGIN:AddContainerType( 8, "Car", 5 );
PLUGIN:AddContainerItem( "bandage", 4 );
PLUGIN:AddContainerItem( "brokenplank", 4 );
PLUGIN:AddContainerItem( "bucket", 4 );
PLUGIN:AddContainerItem( "carbattery", 2 );
PLUGIN:AddContainerItem( "coffee", 3 );
PLUGIN:AddContainerItem( "electronicscrap", 5 );
PLUGIN:AddContainerItem( "gascan", 4 );
PLUGIN:AddContainerItem( "lever", 4 );
PLUGIN:AddContainerItem( "metalplate", 4 );
PLUGIN:AddContainerItem( "money", 2 );
PLUGIN:AddContainerItem( "paper", 2 );
PLUGIN:AddContainerItem( "photo", 3 );
PLUGIN:AddContainerItem( "pliers", 3 );
PLUGIN:AddContainerItem( "radio", 3 );
PLUGIN:AddContainerItem( "soda1", 2 );
PLUGIN:AddContainerItem( "soda2", 2 );
PLUGIN:AddContainerItem( "soda3", 2 );
PLUGIN:AddContainerItem( "skull", 128 );
PLUGIN:AddContainerItem( "spine", 128 );
PLUGIN:AddContainerItem( "survivalguide", 64 );
PLUGIN:AddContainerItem( "takeout", 4 );
PLUGIN:AddContainerItem( "tincan", 3 );
PLUGIN:AddContainerItem( "tireiron", 3 );
PLUGIN:AddContainerItem( "tire", 3 );
PLUGIN:AddContainerItem( "water", 2 );
PLUGIN:AddContainerItem( "wrench", 3 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );
PLUGIN:AddContainerItem( "knife", 7 );

PLUGIN:AddContainerType( 9, "First Aid", 4 );
PLUGIN:AddContainerItem( "bandage", 2 );
PLUGIN:AddContainerItem( "painkillers", 2 );
PLUGIN:AddContainerItem( "antibiotics", 5 );
PLUGIN:AddContainerItem( "zombrex", 30 );

PLUGIN:AddContainerType( 10, "Vending Machine", 2 );
PLUGIN:AddContainerItem( "soda1", 4 );
PLUGIN:AddContainerItem( "soda2", 4 );
PLUGIN:AddContainerItem( "soda3", 4 );
PLUGIN:AddContainerItem( "water", 4 );
PLUGIN:AddContainerItem( "money", 4 );

PLUGIN:AddContainerType( 11, "Dead Body", 3 );
PLUGIN:AddContainerItem( "axe", 8 );
PLUGIN:AddContainerItem( "knife", 7 );
PLUGIN:AddContainerItem( "banana", 6 );
PLUGIN:AddContainerItem( "bandage", 4 );
PLUGIN:AddContainerItem( "bat", 8 );
PLUGIN:AddContainerItem( "brandy", 6 );
PLUGIN:AddContainerItem( "brokenplank", 6 );
PLUGIN:AddContainerItem( "electronicscrap", 2 );
PLUGIN:AddContainerItem( "hammer", 8 );
PLUGIN:AddContainerItem( "money", 2 );
PLUGIN:AddContainerItem( "orange", 6 );
PLUGIN:AddContainerItem( "painkillers", 4 );
PLUGIN:AddContainerItem( "paper", 4 );
PLUGIN:AddContainerItem( "photo", 8 );
PLUGIN:AddContainerItem( "pipe", 8 );
PLUGIN:AddContainerItem( "pliers", 8 );
PLUGIN:AddContainerItem( "pot", 8 );
PLUGIN:AddContainerItem( "rebars", 8 );
PLUGIN:AddContainerItem( "metal", 2 );
PLUGIN:AddContainerItem( "scrapwood", 2 );
PLUGIN:AddContainerItem( "sledge", 8 );
PLUGIN:AddContainerItem( "soda1", 6 );
PLUGIN:AddContainerItem( "soda2", 6 );
PLUGIN:AddContainerItem( "soda3", 6 );
PLUGIN:AddContainerItem( "survivalguide", 16 );
PLUGIN:AddContainerItem( "tireiron", 8 );
PLUGIN:AddContainerItem( "tshirt", 1 );
PLUGIN:AddContainerItem( "zmeat", 1 );
PLUGIN:AddContainerItem( "water", 4 );
PLUGIN:AddContainerItem( "wrench", 8 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );
PLUGIN:AddContainerItem( "rationjar", 6 );

PLUGIN:AddContainerType( 12, "Trash", 4 );
PLUGIN:AddContainerItem( "banana", 4 );
PLUGIN:AddContainerItem( "bananabunch", 4 );
PLUGIN:AddContainerItem( "beer1", 4 );
PLUGIN:AddContainerItem( "beer2", 4 );
PLUGIN:AddContainerItem( "brokenplank", 8 );
PLUGIN:AddContainerItem( "carbattery", 8 );
PLUGIN:AddContainerItem( "cinderblock", 4 );
PLUGIN:AddContainerItem( "doll", 4 );
PLUGIN:AddContainerItem( "electronicscrap", 2 );
PLUGIN:AddContainerItem( "fish", 4 );
PLUGIN:AddContainerItem( "lever", 4 );
PLUGIN:AddContainerItem( "metalplate", 2 );
PLUGIN:AddContainerItem( "milkcarton", 4 );
PLUGIN:AddContainerItem( "milk", 8 );
PLUGIN:AddContainerItem( "orange", 4 );
PLUGIN:AddContainerItem( "paint", 4 );
PLUGIN:AddContainerItem( "paper", 4 );
PLUGIN:AddContainerItem( "photo", 4 );
PLUGIN:AddContainerItem( "plasticbucket", 4 );
PLUGIN:AddContainerItem( "plug", 4 );
PLUGIN:AddContainerItem( "pot", 8 );
PLUGIN:AddContainerItem( "radio", 4 );
PLUGIN:AddContainerItem( "rebars", 2 );
PLUGIN:AddContainerItem( "rock", 8 );
PLUGIN:AddContainerItem( "metal", 2 );
PLUGIN:AddContainerItem( "scrapwood", 2 );
PLUGIN:AddContainerItem( "shoe", 4 );
PLUGIN:AddContainerItem( "skull", 128 );
PLUGIN:AddContainerItem( "spine", 128 );
PLUGIN:AddContainerItem( "survivalguide", 32 );
PLUGIN:AddContainerItem( "takeout", 4 );
PLUGIN:AddContainerItem( "teapot", 4 );
PLUGIN:AddContainerItem( "tincan", 4 );
PLUGIN:AddContainerItem( "tire", 4 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );
PLUGIN:AddContainerItem( "emptyjug", 2 );
PLUGIN:AddContainerItem( "concentratedmilk", 4 );

PLUGIN:AddContainerType( 13, "Ammo Pile", 2 );
PLUGIN:AddContainerItem( "pistol", 80 );
PLUGIN:AddContainerItem( "revolver", 100 );
PLUGIN:AddContainerItem( "shotgun", 120 );
PLUGIN:AddContainerItem( "pistolammo", 32 );
PLUGIN:AddContainerItem( "revolverammo", 32 );
PLUGIN:AddContainerItem( "shotgunammo", 32 );
PLUGIN:AddContainerItem( "rifleammo", 32 );

PLUGIN:AddContainerType( 14, "Dumpster", 2 );
PLUGIN:AddContainerItem( "bleach", 4 );
PLUGIN:AddContainerItem( "bottle1", 4 );
PLUGIN:AddContainerItem( "bottle5", 4 );
PLUGIN:AddContainerItem( "bottle6", 4 );
PLUGIN:AddContainerItem( "bottle9", 4 );
PLUGIN:AddContainerItem( "brokenplank", 8 );
PLUGIN:AddContainerItem( "bucket", 4 );
PLUGIN:AddContainerItem( "cinderblock", 4 );
PLUGIN:AddContainerItem( "doll", 4 );
PLUGIN:AddContainerItem( "drawer", 4 );
PLUGIN:AddContainerItem( "electronicscrap", 2 );
PLUGIN:AddContainerItem( "jarbig", 4 );
PLUGIN:AddContainerItem( "lamp", 4 );
PLUGIN:AddContainerItem( "lampshade", 4 );
PLUGIN:AddContainerItem( "lever", 4 );
PLUGIN:AddContainerItem( "metalplate", 4 );
PLUGIN:AddContainerItem( "milkcarton", 4 );
PLUGIN:AddContainerItem( "paint", 4 );
PLUGIN:AddContainerItem( "paper", 4 );
PLUGIN:AddContainerItem( "photo", 4 );
PLUGIN:AddContainerItem( "pipe", 4 );
PLUGIN:AddContainerItem( "plank", 4 );
PLUGIN:AddContainerItem( "plasticbucket", 4 );
PLUGIN:AddContainerItem( "pliers", 4 );
PLUGIN:AddContainerItem( "plug", 4 );
PLUGIN:AddContainerItem( "pot", 4 );
PLUGIN:AddContainerItem( "rebars", 4 );
PLUGIN:AddContainerItem( "rock", 4 );
PLUGIN:AddContainerItem( "metal", 2 );
PLUGIN:AddContainerItem( "scrapwood", 2 );
PLUGIN:AddContainerItem( "shoe", 4 );
PLUGIN:AddContainerItem( "skull", 128 );
PLUGIN:AddContainerItem( "smallpot", 4 );
PLUGIN:AddContainerItem( "spine", 128 );
PLUGIN:AddContainerItem( "streetsign", 4 );
PLUGIN:AddContainerItem( "takeout", 4 );
PLUGIN:AddContainerItem( "terracotta", 4 );
PLUGIN:AddContainerItem( "tincan", 4 );
PLUGIN:AddContainerItem( "tire", 4 );
PLUGIN:AddContainerItem( "water", 4 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );
PLUGIN:AddContainerItem( "knife", 7 );
PLUGIN:AddContainerItem( "cereal", 2 );
PLUGIN:AddContainerItem( "emptyjug", 2 );

PLUGIN:AddContainerType( 15, "Cash Register", 1 );
PLUGIN:AddContainerItem( "money", 2 );

PLUGIN:AddContainerType( 16, "Desk", 4 );
PLUGIN:AddContainerItem( "money", 4 );
PLUGIN:AddContainerItem( "drawer", 2 );
PLUGIN:AddContainerItem( "painkillers", 6 );
PLUGIN:AddContainerItem( "paper", 2 );
PLUGIN:AddContainerItem( "survivalguide", 32 );
PLUGIN:AddContainerItem( "electronicscrap", 4 );
PLUGIN:AddContainerItem( "metal", 4 );
PLUGIN:AddContainerItem( "scrapwood", 4 );
PLUGIN:AddContainerItem( "craftguide", 32 );

PLUGIN:AddContainerType( 17, "Lockers", 4 );
PLUGIN:AddContainerItem( "bandage", 4 );
PLUGIN:AddContainerItem( "electronicscrap", 4 );
PLUGIN:AddContainerItem( "metal", 4 );
PLUGIN:AddContainerItem( "scrapwood", 4 );
PLUGIN:AddContainerItem( "money", 4 );
PLUGIN:AddContainerItem( "paper", 4 );
PLUGIN:AddContainerItem( "photo", 4 );
PLUGIN:AddContainerItem( "shoe", 2 );
PLUGIN:AddContainerItem( "tshirt", 2 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "craftguide", 32 );

PLUGIN:AddContainerType( 18, "Filing Cabinet", 4 );
PLUGIN:AddContainerItem( "paper", 2 );
PLUGIN:AddContainerItem( "money", 4 );
PLUGIN:AddContainerItem( "craftguide", 32 );

PLUGIN:AddContainerType( 19, "Warehouse", 6 );
PLUGIN:AddContainerItem( "axe", 8 );
PLUGIN:AddContainerItem( "bandage", 4 );
PLUGIN:AddContainerItem( "bat", 8 );
PLUGIN:AddContainerItem( "beer1", 4 );
PLUGIN:AddContainerItem( "beer2", 4 );
PLUGIN:AddContainerItem( "bleach", 4 );
PLUGIN:AddContainerItem( "bottle1", 4 );
PLUGIN:AddContainerItem( "bottle5", 4 );
PLUGIN:AddContainerItem( "bottle6", 4 );
PLUGIN:AddContainerItem( "bottle9", 4 );
PLUGIN:AddContainerItem( "brandy", 4 );
PLUGIN:AddContainerItem( "bucket", 4 );
PLUGIN:AddContainerItem( "carbattery", 4 );
PLUGIN:AddContainerItem( "doll", 4 );
PLUGIN:AddContainerItem( "electronicscrap", 2 );
PLUGIN:AddContainerItem( "metal", 2 );
PLUGIN:AddContainerItem( "scrapwood", 2 );
PLUGIN:AddContainerItem( "extinguisher", 4 );
PLUGIN:AddContainerItem( "gascan", 4 );
PLUGIN:AddContainerItem( "hammer", 4 );
PLUGIN:AddContainerItem( "jarbig", 4 );
PLUGIN:AddContainerItem( "lamp", 4 );
PLUGIN:AddContainerItem( "lever", 4 );
PLUGIN:AddContainerItem( "metalplate", 4 );
PLUGIN:AddContainerItem( "money", 8 );
PLUGIN:AddContainerItem( "painkillers", 4 );
PLUGIN:AddContainerItem( "paint", 4 );
PLUGIN:AddContainerItem( "paper", 4 );
PLUGIN:AddContainerItem( "pipe", 4 );
PLUGIN:AddContainerItem( "plasticbucket", 4 );
PLUGIN:AddContainerItem( "pliers", 4 );
PLUGIN:AddContainerItem( "plug", 4 );
PLUGIN:AddContainerItem( "pot", 8 );
PLUGIN:AddContainerItem( "propane", 4 );
PLUGIN:AddContainerItem( "radio", 4 );
PLUGIN:AddContainerItem( "rebars", 4 );
PLUGIN:AddContainerItem( "shoe", 4 );
PLUGIN:AddContainerItem( "sledge", 8 );
PLUGIN:AddContainerItem( "smallpot", 4 );
PLUGIN:AddContainerItem( "survivalguide", 16 );
PLUGIN:AddContainerItem( "teapot", 4 );
PLUGIN:AddContainerItem( "terracotta", 4 );
PLUGIN:AddContainerItem( "tincan", 4 );
PLUGIN:AddContainerItem( "tire", 4 );
PLUGIN:AddContainerItem( "tireiron", 8 );
PLUGIN:AddContainerItem( "toothbrushes", 4 );
PLUGIN:AddContainerItem( "tshirt", 4 );
PLUGIN:AddContainerItem( "whiskey", 4 );
PLUGIN:AddContainerItem( "wrench", 8 );
PLUGIN:AddContainerItem( "cannedmeat", 2 );
PLUGIN:AddContainerItem( "rationjar", 4 );

PLUGIN:AddContainerType( 20, "Cigarette Vending Machine", 1 );
PLUGIN:AddContainerItem( "money", 4 );

PLUGIN:AddContainerType( 21, "Medical Supplies", 12 );
PLUGIN:AddContainerItem( "bandages", 2 );
PLUGIN:AddContainerItem( "painkillers", 2 );
PLUGIN:AddContainerItem( "paper", 4 );
PLUGIN:AddContainerItem( "water", 3 );

PLUGIN:AddContainerType( 22, "Book Shelf", 2 );
PLUGIN:AddContainerItem( "craftguide", 16 );
PLUGIN:AddContainerItem( "survivalguide", 16 );

PLUGIN:AddContainerType( 23, "test", 4);
PLUGIN:AddContainerItem( "Brick", 1 );